### ISSUE TITLE
String concatenation the PHP-way in generate-php.js

### ISSUE THREAD

**Issue by bdjantl** [MarcelBolten/phpeggy#1]
https://github.com/MarcelBolten/phpeggy/blob/ee3d27d0bd76a48c570cd596e063eb740fa1db01/src/passes/generate-php.js#L838

String concatenation is the javascript way (string + string...), should be string . string (string dot string) instead.

**Comment by MarcelBolten** [comment]
Hi @bdjantl 
Thanks for reporting.
It is already fixed in the develop branch.
I will publish a fix soon.
